### ISSUE TITLE
Update pubsub subscriber to use ReportMessage from k8s.io/test-infra

### ISSUE THREAD

**Issue by yt3liu** [knative/test-infra#912]
Attempted to resolved dependencies manually by adding override fields in Gopkg.toml. the override versions are based on dependency version in [k8s/test-infra](https://github.com/kubernetes/test-infra/blob/b04708f9255f109196389baa71dcf93c0c8b65cd/go.mod)

<details><summary>Changes in Gopkg.toml</summary>
<p>

Overrides added: 

```
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v10.15.5"

[[override]]
  name = "github.com/fsnotify/fsnotify"
  version = "v1.4.7"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.3.1"

[[override]]
  name = "github.com/gomodule/redigo"
  version = "v1.7.0"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "bdd8b1ecd793ffb03d43314c66565be3d6a7a582"

[[override]]
  name = "github.com/gregjones/httpcache"
  revision = "3befbb6ad0cc97d4c25d851e9528915809e1a22f"

[[override]]
  name = "github.com/knative/build"
  revision = "38ace00371c775ef5e70f83f1ffbae0cfd6cf47d"

[[override]]
  name = "github.com/knative/pkg"
  revision = "916205998db9d085aaff357221b208bc89290ea5"

[[override]]
  name = "github.com/prometheus/common"
  version = "v0.4.1"

[[override]]
  name = "github.com/prometheus/procfs"
  version = "v0.0.1"

[[override]]
  name = "github.com/shurcooL/githubv4"
  version = "51d7b505e2e9434db74794b52222c13253209955"

[[override]]
  name = "github.com/tektoncd/pipeline"
  revision = "7c43fbae2816c7271bed51098d0595cd6174c7a3"

[[override]]
  name = "k8s.io/client-go"
  version = "v9.0.0"
```

Error (persisted even after clearing dep cache and removing vendor directory)
```
/github.com/knative/test-infra$ ./hack/update-deps.sh 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/golang/dep/gps.(*solver).findValidVersion(0xc000595000, 0xc0010f8e60, 0xc00014ee00, 0x7, 0x7, 0x0, 0xc00014ee00)
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/gps/solver.go:945 +0x4cc
github.com/golang/dep/gps.(*solver).backtrack(0xc000595000, 0xbffda0, 0xc00002a0f0, 0x0, 0x0, 0x0)
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/gps/solver.go:1079 +0xbdc
github.com/golang/dep/gps.(*solver).solve(0xc000595000, 0xbffda0, 0xc00002a0f0, 0x5, 0xc0001baa48, 0xc00044f548)
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/gps/solver.go:510 +0x872
github.com/golang/dep/gps.(*solver).Solve(0xc000595000, 0xbffda0, 0xc00002a0f0, 0x104f058, 0xc00002c07a, 0x1d, 0xc0003e7a40)
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/gps/solver.go:440 +0x1eb
main.(*ensureCommand).runDefault(0xc000161720, 0xc0000d4880, 0xc00000f720, 0x0, 0x0, 0xc0000d1200, 0xc07d00, 0xc00007eea0, 0xc00002c054, 0x43, ...)
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/cmd/dep/ensure.go:281 +0x3fb
main.(*ensureCommand).Run(0xc000161720, 0xc0000d4880, 0xc00000f720, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/cmd/dep/ensure.go:218 +0x80e
main.(*Config).Run(0xc00007eea0, 0x0)
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/cmd/dep/main.go:212 +0x111c
main.main()
	/usr/local/google/home/joyceyu/go/src/github.com/golang/dep/cmd/dep/main.go:84 +0x636

```

</p>
</details>

Dep version override reference: https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#dependency-rules-constraint-and-override

Potential solution: 
1. Keep making changes to Gopkg.toml until all errors are resolved 
1. This may be fixed after test-infra is using go modules instead of dep

**Comment by srinivashegde86** [comment]
I looked into this a bit. Looks like prow is dependent on tekton for a few things and tekton is using knative/pkg as of 2/14 - https://github.com/tektoncd/pipeline/blob/3e8b177fbeb39126a9c9de121008db571ef45bfa/Gopkg.toml#L57

That seems too old and pkg has had a few changes in that time and we are seeing issues building tekton with an updated version of pkg. Mainly, it does not completely implement the common interfaces
```
vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/cluster_task_types.go:43:5: cannot use (*ClusterTask)(nil) (type *ClusterTask) as type apis.Validatable in assignment:
	*ClusterTask does not implement apis.Validatable (wrong type for Validate method)
		have Validate(context.Context) *apis.FieldError
		want Validate() *apis.FieldError
vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/cluster_task_types.go:44:5: cannot use (*ClusterTask)(nil) (type *ClusterTask) as type apis.Defaultable in assignment:
	*ClusterTask does not implement apis.Defaultable (wrong type for SetDefaults method)
		have SetDefaults(context.Context)
		want SetDefaults()
```

Ideally, tekton would update to latest pkg/ or more a recent one and we can just pull them in.

**Comment by srinivashegde86** [comment]
Tried updating pkg/ to 2/14, but we have added a few things in there, that we need form that time :(
```
Solving failure: No versions of github.com/knative/pkg met constraints:
	0183bf9cdc7349e3c76c26e51f84689b411fccea: Could not introduce github.com/knative/pkg@0183bf9cdc7349e3c76c26e51f84689b411fccea, as its subpackage github.com/knative/pkg/test/monitoring is missing. (Package is required by (root).)
	master: Could not introduce github.com/knative/pkg@master, as it is not allowed by constraint 0183bf9cdc7349e3c76c26e51f84689b411fccea from project github.com/knative/test-infra.
	master: Could not introduce github.com/knative/pkg@master, as it is not allowed by constraint 0183bf9cdc7349e3c76c26e51f84689b411fccea from project github.com/knative/test-infra.```

**Comment by srinivashegde86** [comment]
tektoncd has updated to knative.dev/pkg, but looks like k8s.io/test-infra is still using the old name causing build issues

**Comment by adrcunha** [comment]
This circular dependency between Prow and Knative is insane. @krzyzacy @cjwagner any comments on this?

**Comment by srinivashegde86** [comment]
Looks like the tekton dependency needs to be updated to latest in k8s/test-infra this as the pipeline version in their vendor dir sitll uses the old github.com/knative/pkg. This commit updated it tektoncd/pipeline@5021e4d#diff-a5b024c3ad8012899d9a7d56f19c2331, but they still dont have a release with it and I think we should wait till they are ready with it to upgrade.

**Comment by srinivashegde86** [comment]
@bobcatfish
