### ISSUE TITLE
gubernator crashes when opening 32MB+ logs

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#981]
Usually that happens when opening the test log form GitHub. For example:

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/4338/pull-knative-serving-integration-tests/1141568502964948993/

throws

```
Internal Server Error
The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~knative-tests/gubernator:v20180917-9fc51e109-dirty.412643054916464390/view_base.py", line 85, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~knative-tests/gubernator:v20180917-9fc51e109-dirty.412643054916464390/view_build.py", line 252, in get
    build_log = get_build_log(build_dir)
  File "/base/data/home/apps/s~knative-tests/gubernator:v20180917-9fc51e109-dirty.412643054916464390/view_base.py", line 132, in wrapped
    data = func(*args)
  File "/base/data/home/apps/s~knative-tests/gubernator:v20180917-9fc51e109-dirty.412643054916464390/view_build.py", line 100, in get_build_log
    build_log = gcs_async.read(build_dir + '/build-log.txt').get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~knative-tests/gubernator:v20180917-9fc51e109-dirty.412643054916464390/gcs_async.py", line 45, in get
    result = yield context.urlfetch(url, headers=headers)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 1305, in urlfetch
    result = yield rpc
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 513, in _on_rpc_completion
    result = rpc.get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 615, in get_result
    return self.__get_result_hook(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/500e2bb923862643/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 453, in _get_fetch_result
    + url + error_detail)
DownloadError: Unspecified error in fetching URL: https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_serving/4338/pull-knative-serving-integration-tests/1141568502964948993/build-log.txt
```

However, https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_serving/4338/pull-knative-serving-integration-tests/1141568502964948993/build-log.txt is readable.

Artifacts are here:

https://console.cloud.google.com/storage/browser/knative-prow/pr-logs/pull/knative_serving/4338/pull-knative-serving-integration-tests/1141568502964948993?project=knative-tests

**Comment by adrcunha** [comment]
I just noticed that the above log is 37MB long.

**Comment by adrcunha** [comment]
According to https://cloud.google.com/appengine/docs/standard/python/outbound-requests the URL Fetch service has a limit of 32MB for response size.

**Comment by adrcunha** [comment]
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/4338/pull-knative-serving-integration-tests/1139273583915175937/ points to a 15MB and doesn't cause the 500 above.

**Comment by adrcunha** [comment]
Since this is an API limitation, looks like the solution is to switch to Spyglass (#710).

**Comment by adrcunha** [comment]
Closing in favor of #710.
